### ISSUE TITLE
Unable to build the app

### ISSUE THREAD

**Issue by pandeyVishakha** [kuuuurt/rick-and-morty-app#1]
Hi,
I just tried to take a clone and run the application ,but there is an error like

/////
Gradle sync failed: This version of Android Studio cannot open this project, please retry with Android Studio 3.5 or newer.
////

But this studio version is not stable , am tried to update my studio but the latest stable version is
3.4.2.
How I can build this app in lower version of android studio???

**Comment by kuuuurt** [comment]
Hello! Yeah. I built this using the 3.5 from the Beta Channel. Unfortunately, you can't build this using AS 3.4. Maybe you could play around and change the gradle configurations so that it could work for 3.4. If not, maybe this is your chance to try out 3.5.

**Comment by pandeyVishakha** [comment]
Okay , Thanks for letting me know!!
